<?php

function emic_canvas_menu() {
  $items = array();
  $items['emic/shared/test'] = array(
    'page callback' => 'build_manifest',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'build_sharedcanvas_streams.inc',
  );

  $items['emic/shared/setup'] = array(
    'page callback' => 'islandora_canvas_setup',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'emic_canvas_callbacks.inc',
  );

  $items['emic/shared/add_annotation'] = array(
    'page callback' => 'islandora_add_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'emic_canvas_callbacks.inc',
  );

  $items['emic/get_urns'] = array(
    'page callback' => 'islandora_shared_get_annotation_urns',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'emic_canvas_callbacks.inc',
  );

  $items['emic/get_annotation'] = array(
    'page callback' => 'islandora_shared_get_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'emic_canvas_callbacks.inc',
  );
  $items['emic/delete_annotation'] = array(
    'page callback' => 'islandora_delete_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'emic_canvas_callbacks.inc',
  );
  $items['emic/update_annotation'] = array(
    'page callback' => 'emic_canvas_update_annotation',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'emic_canvas_callbacks.inc',
  );

  $items['emic/serve'] = array(
    'page callback' => 'emic_serve',
    'type' => MENU_CALLBACK,
    'access arguments' => array('view fedora collection'),
    'file' => 'build_sharedcanvas_streams.inc',
  );

  return $items;
}

function emic_canvas_required_fedora_objects() {
  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
  $module_path = drupal_get_path('module', 'islandora_book');
  return array(
    'islandora_book' => array(
      'module' => 'emic_canavas',
      'title' => 'Emic Shared Canvas',
      'objects' => array(
        array(
          'foxml_file' => "$module_path/xml/islandora_criticalEditionPage.xml",
          'pid' => 'islandora:criticalEditionCModelPage',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
      ),
    ),
  );
}